# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal -- NUnit.TestOutputXml=test-result

    # - name: Cloning another repo
    #   run: git clone https://github.com/preetham-coupa/GitHubActionTest.git
    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: preetham-coupa/GitHubActionTest
        ref: main
    - name: Print Path
      run: ls;
    - name: Run Test on Cloned Repo
      run: dotnet restore; dotnet build --no-restore; dotnet test --no-build --verbosity normal -- NUnit.TestOutputXml=test-result-another;

    - name: Publish Test Results of Unit Test
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "**/Debug/*/test-result/*.xml"

    - name: Print Path
      run: ls; cd NUnitTestProjectForGitHubActionTest/bin/Debug/net6.0/test-result-another; ls;
    - name: Generate HTML test report
      uses: rempelj/nunit-html-action@v1.0.1
      if: always()
      with:
        inputXmlPath: GitHubActionTest/NUnitTestProjectForGitHubActionTest/bin/Debug/net6.0/test-result-another/NUnitTestProjectForGitHubActionTest.xml
        outputHtmlPath: GitHubActionTest/NUnitTestProjectForGitHubActionTest/bin/Debug/net6.0/test-result-another/NUnitTestProjectForGitHubActionTest.html
          #  "GitHubActionTest/**/Debug/*/test-result-another/*.xml"
